### PR TITLE
refactor(global): Typescript conversion

### PR DESCRIPTION
**Pull request by s0j0hn**
Standalone launch: done
Tests: done
Pipeline & scripts: done

### CODE REVIEW

**Comment by s0j0hn** [comment]
Will need some help on resolving these merge conflicts @PierreBrisorgueil

**Comment by PierreBrisorgueil** [comment]
i'will have a look on it today

**Comment by PierreBrisorgueil** [comment]
@s0j0hn you juste have to rebase it https://anavarre.net/how-to-rebase-a-github-pull-request/ 

you will have a merge with some actions in package.json, fort package-lock just delete it and npm i again

**Comment by s0j0hn** [comment]
> @s0j0hn you juste have to rebase it https://anavarre.net/how-to-rebase-a-github-pull-request/
> 
> you will have a merge with some actions in package.json, fort package-lock just delete it and npm i again

Should be good now

**Comment by PierreBrisorgueil** [comment]
Hum, couldn't start on my side, but rebase ok 👌
Don't hesitate if you want help, I have little time but I can help if you get stuck :)

**Pull request merged**
